### ISSUE TITLE
Libraries update

### ISSUE THREAD

**Issue by purumpum** [slok/algs4-mvn-repo#4]
As described at http://algs4.cs.princeton.edu/code/, the authors have merged IO and algorithms libraries and moved classes into the package 'edu.princeton.cs.algs4'.

It seems that old libraries (uses the default package) are not supported by Coursera's autograder anymore.

**Comment by slok** [comment]
Can you create a pull request with the new libraries? That would be awesome :)

**Comment by AndrewEvdokimov** [comment]
Ok, in a day or two I will provide a pull request

вторник, 8 сентября 2015 г. пользователь Xabier Larrakoetxea Gallego
написал:

**Comment by purumpum** [comment]
Libraries was updated with merge of pull request #5.
